---
- hosts: all 
  remote_user: root
  become: yes
  tasks:
  - name: install zabbix repo
    shell: rpm -Uvh https://repo.zabbix.com/zabbix/3.0/rhel/7/x86-64/zabbix-release-3.0-1.el7.noarch.rpm
    ignore_errors: True
  - name: install zabbix-agent
    yum: 
      name: zabbix-agent
      state: latest
  - name:
    service:
       name: zabbix-agent
       state: started
       enabled: yes
